### PR TITLE
disable hive server and hwi if kerberos is enable

### PR DESCRIPTION
**Pull request by alexliu68**

### CODE REVIEW

**Comment by mbulman** [comment]
Is there a way we can achieve this without extending how much we're forking hive?  Are we even forking it at all before this?

**Comment by alexliu68** [comment]
We have forked hive long time ago, so it's easy to change the code. There is no plan to contribute all our changes back to hive. 

The code won't break existing code and they should be removed once Hive server and HWI supports kerberos.

The other way to disable the hive server and hwi is to change the shell scripts.  Everyone can change the shell script, it's not secure.  Also to read the security setting from dse.yaml is not good coding in shell scripts.

**Comment by mbulman** [comment]
Change messages to:

Hive server cannot be run when security is enabled (kerberos authentication).

Hive web interface cannot be run when security is enabled (kerberos authentication).

**Comment by beobal** [comment]
What sets the kerberos.enable system property, is it done by Hadoop if the auth type is set to "kerberos"?

**Comment by alexliu68** [comment]
The kerberos.enable system property is set in DSE config.

**Comment by beobal** [comment]
Fair enough. 
Can you change to use Boolean.getBoolean() + constants as you did in Solr?

**Comment by beobal** [comment]
+1

**Pull request merged**
